# Generated by Django 4.1.4 on 2023-02-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_contact_us_order_tag_orderitem_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
